# Generated by Django 6.0.6 on 2026-09-26 21:51

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0003_product_is_featured'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='What customers type. Not case-sensitive.', max_length=30, unique=True, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9-]+$', 'Use letters, digits, and hyphens only.')])),
                ('description', models.CharField(blank=True, help_text='For staff only, e.g. the campaign it belongs to.', max_length=200)),
                ('kind', models.CharField(choices=[('PERCENT', 'Percent off'), ('AMOUNT', 'Amount off')], default='PERCENT', max_length=7)),
                ('value', models.DecimalField(decimal_places=2, help_text='A percentage (1–100) or a dollar amount, depending on the kind.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('min_spend', models.DecimalField(blank=True, decimal_places=2, help_text='Optional. The cart subtotal must reach this amount.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='minimum spend')),
                ('is_active', models.BooleanField(default=True, help_text='Switch off to retire the code immediately.', verbose_name='active')),
                ('starts_on', models.DateField(blank=True, help_text='Optional. First day the code works.', null=True)),
                ('ends_on', models.DateField(blank=True, help_text='Optional. Last day the code works.', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('product', models.ForeignKey(blank=True, help_text='Leave blank to discount the whole order.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='coupons', to='products.product')),
            ],
            options={
                'ordering': ['code'],
                'constraints': [models.CheckConstraint(condition=models.Q(('value__gt', 0)), name='coupon_value_positive'), models.CheckConstraint(condition=models.Q(('kind', 'AMOUNT'), ('value__lte', 100), _connector='OR'), name='coupon_percent_at_most_100'), models.CheckConstraint(condition=models.Q(('starts_on__isnull', True), ('ends_on__isnull', True), ('ends_on__gte', models.F('starts_on')), _connector='OR'), name='coupon_window_in_order')],
            },
        ),
    ]
